title: ART
author: SpaceSquibble
email: DM me, i don't have an email
description: > # this means to ignore newlines until "baseurl:"
  This page will showcase my digital art.

# social links
instagram_username: @spacesquibble

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
